"""What the builder compiles and runs for the rate limiter. The page content is in problem.py."""

SLUG = 'rate-limiter'
NAME = 'Rate limiter'
TITLE = 'Rate limiter · LLD workbench'
SUBTITLE = 'LLD workbench · Java 17 · every class on this page compiles and runs'

# Snapshots of the one source tree (see ../snap.py): the core, then one per follow-up, in the
# order the follow-ups build on each other. Named after their step, never numbered.
SNAPS = ['core', 'windows', 'newrule', 'credits', 'idle']

# The core, in the order it is typed in the room: top-down, from the front door to where the
# counts live, the caller before its parts. A step whose parts come later is not compiled on its
# own (compile=False); `alone` compiles a step with just the files it needs.
BUILD = [
    dict(id='door', files=['Request.java', 'RateLimitResult.java', 'RateLimiter.java',
                           'RateLimitFilter.java']),
    dict(id='limiter', files=['RuleBasedRateLimiter.java', 'Clock.java'], compile=False),
    dict(id='rules', files=['RateLimitRule.java', 'Match.java', 'Caller.java', 'CountPer.java',
                            'ScoreApiRules.java'],
         compile=False),
    dict(id='limits', files=['Limit.java', 'LimitPolicy.java', 'FixedLimit.java', 'PlanLimit.java',
                             'Plan.java', 'Customers.java'],
         alone=['Request.java', 'Limit.java', 'LimitPolicy.java', 'FixedLimit.java',
                'PlanLimit.java', 'Plan.java', 'Customers.java']),
    dict(id='counters', files=['Decision.java', 'Counter.java', 'TokenBucket.java',
                               'FixedWindowCounter.java', 'SlidingWindowLog.java', 'Algorithm.java',
                               'CounterFactory.java'],
         alone=['Limit.java', 'RateLimitResult.java', 'Decision.java', 'Counter.java', 'TokenBucket.java',
                'FixedWindowCounter.java', 'SlidingWindowLog.java', 'Algorithm.java',
                'CounterFactory.java'],
         demo='BucketDemo'),
    dict(id='store', files=['CounterStore.java', 'InMemoryCounterStore.java'], demo='StoreDemo'),
    dict(id='run', files=['Main.java'], demo='Main'),
]

# The demo each follow-up runs (it checks its own numbers; see demos/Check.java).
DEMOS = {'windows': 'WindowsDemo', 'newrule': 'NewRuleDemo', 'credits': 'CreditsDemo',
         'idle': 'IdleDemo'}

# Extra programs run against a snapshot: their output answers questions elsewhere on the page.
EXTRA = [('QuizDemo', 'core'), ('CountingDemo', 'core')]

CORE_TYPES = ['Request', 'RateLimitResult', 'RateLimiter', 'RateLimitFilter',
              'RuleBasedRateLimiter', 'Clock', 'RateLimitRule', 'Match', 'Caller', 'CountPer',
              'ScoreApiRules',
              'Limit', 'LimitPolicy', 'FixedLimit', 'PlanLimit', 'Plan', 'Customers', 'Decision',
              'Counter', 'TokenBucket', 'FixedWindowCounter', 'SlidingWindowLog', 'Algorithm',
              'CounterFactory', 'CounterStore', 'InMemoryCounterStore', 'Main']
FILE_ORDER = [t + '.java' for t in CORE_TYPES] + [t + '.java' for t in [
    'SlidingWindowCounter', 'CreditWindow']]

STRIP = [
    ('the door', ['Request', 'RateLimitResult', 'RateLimiter', 'RateLimitFilter']),
    ('the limiter', ['RuleBasedRateLimiter', 'Clock']),
    ('the rules', ['RateLimitRule', 'Match', 'Caller', 'CountPer', 'ScoreApiRules']),
    ('how much', ['Limit', 'LimitPolicy', 'FixedLimit', 'PlanLimit', 'Plan', 'Customers']),
    ('counting', ['Decision', 'Counter', 'TokenBucket', 'FixedWindowCounter', 'SlidingWindowLog',
                  'Algorithm', 'CounterFactory']),
    ('where counts live', ['CounterStore', 'InMemoryCounterStore']),
    ('run', ['Main']),
]

MUTANTS = []

# Written next to the page as rate-limiter-code/README.md, with the runnable projects.
EXPORT_README = """# Rate limiter: the code, ready to run

The code from `rate-limiter-workbench.html`, generated by `workbench/build.py` from the same
sources, so it always matches the page.

| folder | what is in it |
|---|---|
| `core/` | the core from the page's build steps, with `Main` |
| `complete/` | the core plus every follow-up, with each follow-up's demo ({demos}) |
| `steps/<step>/` | the code exactly as it is after each follow-up: start a follow-up drill here |

Each folder is a plain Maven project (Java 17, no dependencies). In IntelliJ: File > Open, pick
the folder, then run `Main`.

From a terminal, without Maven:

```
cd core
javac -d out src/main/java/*.java
java -cp out Main
```
"""

CONFIG = dict(SLUG=SLUG, NAME=NAME, TITLE=TITLE, SUBTITLE=SUBTITLE, SNAPS=SNAPS, BUILD=BUILD,
              DEMOS=DEMOS, FILE_ORDER=FILE_ORDER, STRIP=STRIP, MUTANTS=MUTANTS,
              CORE_TYPES=CORE_TYPES, EXTRA=EXTRA, EXPORT_README=EXPORT_README)
